project_id = "ueeojbdtuqsheokmnfsn"

[functions.evaluate-project]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-message]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.verify-id-card]
verify_jwt = true

[functions.verify-phone-otp]
verify_jwt = true

[functions.firebase-config]
verify_jwt = false

[functions.paymob-initiate]
verify_jwt = true

[functions.whatsapp-otp-send]
verify_jwt = true

[functions.whatsapp-otp-verify]
verify_jwt = true

[functions.admin-bootstrap]
verify_jwt = false
